### ISSUE TITLE
Question: Wouldn't this trigger VAC?

### ISSUE THREAD

**Issue by kamikazechaser** [Sumandora/cs2_one_byte_wallhack#1]
I assume the game can monitor access to /proc/self/mem based on the VAC snap process module (which probably uses inotify)?

I'm just curious into the workings of VAC and doing a bit of research around it.

**Comment by Sumandora** [comment]
No, the snapprocess module does not use inotify, in fact VAC does not use inotify at all. Theoretically snapprocess would find the change in .text, however I haven't heard of any case where changing .text actually gets you banned. I didn't really try to avoid vac with this, just toying around and trying to see how easy a wall hack can be. I also have had multiple people try this and nobody got banned from it. I'm not saying it is undetected, but it at least doesn't seem to get you banned at the moment. But yes, if you were to monitor /proc/$/mem, then this would be detected.

**Comment by kamikazechaser** [comment]
Thanks for the insight!

I just re-read the blog (https://lwss.github.io/State-Of-Vac-linux-2020/) section of the snap process and it seems writes would be detected since VAC opens and uploads those files. I'm actually surprised they aren't monitoring read events to /proc/self/mem given that it doesn't even require high privileges.
