### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ParanoIIa91** [Sumandora/cs2_one_byte_wallhack#2]
How exactly do you use it on Linux?

**Comment by Sumandora** [comment]
`cargo run`?

**Comment by ParanoIIa91** [comment]
![Screenshot_20241208_005229](https://github.com/user-attachments/assets/a5fd0fb2-9a75-4c07-907e-1318517985f1)

**Comment by ParanoIIa91** [comment]
Unknown command

**Comment by Sumandora** [comment]
Not related to this repo. Please inform yourself else-where on how to install a rust compiler.

**Comment by ParanoIIa91** [comment]
So, how do you use it?
